spring.application.name=security

spring.jpa.open-in-view=true

#h2 connection configuration

spring.datasource.url=jdbc:postgresql://localhost:5432/user_api_crud
spring.datasource.username=user_api
spring.datasource.password=123456

#SQL show configuration
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update

#jwt configuration
jwt.secret=-0d4HGNuBjsR2Byb4fcG_8zGnirjAdDs_skgM0LU2ZE
jwt.expiration=360000